# Generated by Django 5.1.5 on 2025-01-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.TextField(null=True, unique=True, verbose_name='SLUG'),
        ),
    ]
